### ISSUE TITLE
Checkout the new dolby API

### ISSUE THREAD

**Issue by balauru** [Agilefreaks/SubSonic8#77]
As a Windows 8 app developer, you can now include one of the world’s most advanced, recognizable, and trusted entertainment experiences directly in your apps. If you are a Windows® 8 developer, you're in a unique position to utilize our genuine Dolby® Digital Plus™ technology. Dolby Digital Plus is included in every single Windows 8 system (including Windows RT). This means you simply enable the feature in your app and deliver the Dolby experience for your customers. Take a look at the code samples and Dolby encoded demo content below.

http://developer.dolby.com/tools-tech.aspx

**Comment by cristi-badila** [comment]
The Dolby technology is automatically used when using the native windows playback (which we do)
